from enum import StrEnum
    
class Sector(StrEnum):
    '''
    enumerations for sector selections
    '''
    TECHNOLOGY = "Technology"
    LIFE_SCIENCES = "Life Sciences"
    ENERGY = "Energy"
    MANUFACTURING = "Manufacturing"
    TRADE_AND_SERVICES = "Trade & Services"
    INDUSTRIAL_APPLICATIONS_AND_SERVICES = "Industrial Applications & Services"
    NO_INDUSTRY = "No Industry"
    REAL_ESTATE_AND_CONSTRUCTION = "Real Estate & Construction"
    FINANCIALS = "Financials"

class Ratio(StrEnum):
    '''
    enumerations for ratios selections
    '''
    CyclicallyAdjustedPERatio = "capei"
    BookEquity = "be"
    BookToMarket = "bm"
    EnterpriseValueToMarketCap = "evm"
    PriceToOperatingEarningsBasic = "pe_op_basic"
    PriceToOperatingEarningsDiluted = "pe_op_dil"
    PriceToEarningsExclItems = "pe_exi"
    PriceToEarningsInclItems = "pe_inc"
    PriceToSales = "ps"
    PriceToCashFlow = "pcf"
    DividendPayoutRatio = "dpr"
    NetProfitMargin = "npm"
    OperatingMarginBeforeDep = "opmbd"
    OperatingMarginAfterDep = "opmad"
    GrossProfitMargin = "gpm"
    PretaxProfitMargin = "ptpm"
    CashFlowMargin = "cfm"
    ReturnOnAssets = "roa"
    ReturnOnEquity = "roe"
    ReturnOnCapitalEmployed = "roce"
    EffectiveTaxRate = "efftax"
    AfterTaxReturnOnEquity = "aftret_eq"
    AfterTaxReturnOnInvestedCapital = "aftret_invcapx"
    AfterTaxReturnOnEquityAlt = "aftret_equity"
    PretaxReturnOnNetOperatingAssets = "pretret_noa"
    PretaxReturnOnEarningsAssets = "pretret_earnat"
    GrossProfitability = "gprof"
    EquityToInvestedCapital = "equity_invcap"
    DebtToInvestedCapital = "debt_invcap"
    TotalDebtToInvestedCapital = "totdebt_invcap"
    CapitalizationRatio = "capital_ratio"
    InterestBearingDebt = "int_debt"
    InterestToTotalDebt = "int_totdebt"
    CashToLongTermDebt = "cash_lt"
    InventoryToAssets = "invt_act"
    ReceivablesToAssets = "rect_act"
    DebtToAssets = "debt_at"
    DebtToEBITDA = "debt_ebitda"
    ShortTermDebt = "short_debt"
    CurrentDebt = "curr_debt"
    LongTermDebt = "lt_debt"
    ProfitToLiabilities = "profit_lct"
    OperatingCashFlowToLiabilities = "ocf_lct"
    CashToDebt = "cash_debt"
    FreeCashFlowToOCF = "fcf_ocf"
    LongTermAssetsToPPE = "lt_ppent"
    LongTermDebtToBookEquity = "dltt_be"
    DebtToTotalAssets = "debt_assets"
    DebtToCapital = "debt_capital"
    DebtToEquity = "de_ratio"
    InterestCoverage = "intcov"
    InterestCoverageRatio = "intcov_ratio"
    CashRatio = "cash_ratio"
    QuickRatio = "quick_ratio"
    CurrentRatio = "curr_ratio"
    CashConversionCycle = "cash_conversion"
    InventoryTurnover = "inv_turn"
    AssetTurnover = "at_turn"
    ReceivablesTurnover = "rect_turn"
    PayablesTurnover = "pay_turn"
    SalesToInvestedCapital = "sale_invcap"
    SalesToEquity = "sale_equity"
    SalesToNetWorkingCapital = "sale_nwc"
    RnDToSales = "rd_sale"
    AdvertisingToSales = "adv_sale"
    StaffCostsToSales = "staff_sale"
    Accruals = "accrual"
    ReturnCRSP = "ret_crsp"
    GICSector = "gsector"
    GICDescription = "gicdesc"
    MarketCap = "mktcap"
    Price = "price"
    PriceToBook = "ptb"
    PEGTrailing = "peg_trailing"
    DividendYield = "divyield"