[tool.poetry]
name = "db-helper"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.9"
sqlalchemy = "^2.0"
pandas = "^2.0"
diskcache = "^5.0"
python-dotenv = "^1.0"
tqdm = "^4.0"
mysqlclient = "^2.0"
